# Generated by Django 4.2.6 on 2023-10-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0004_user_info_raffle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ruffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
