# Generated by Django 4.2.6 on 2023-10-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0005_ruffle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ruffle',
            new_name='raffle',
        ),
    ]
