# Generated by Django 4.2.6 on 2023-10-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0007_user_info_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
